# Generated by Django 2.2.12 on 2021-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.CharField(default='Type Here', max_length=100),
        ),
    ]
